name: GitOps.PullRequestIssueManagement
description: Create publishing pull requests
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Push to live branch (scheduled publish)
      frequencies:
      - hourly:
          hour: 3
      filters: []
      actions:
      - createPullRequest:
          head: main
          base: live
          title: Merge main into live
          body: Please don't squash-merge this PR.
    eventResponderTasks:
    - description: Label main to live PRs
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: dotnet-policy-service
          issueAuthor: False
      - titleContains:
          pattern: Merge main into live
          isRegex: False
      - targetsBranch:
          branch: live
      then:
      - addLabel:
          label: ':octocat: auto-merge'
    - description: Auto-merge PRs to live with title "Merge main into live"
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: dotnet-policy-service
          issueAuthor: False
      - titleContains:
          pattern: Merge main into live
          isRegex: False
      - targetBranch:
          branch: live
      - hasLabel:
          label: ':octocat: auto-merge'
      then:
      - enableAutoMerge:
          mergeMethod: Merge
    - description: Don't auto-merge PRs with auto-merge label removed
      if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: ':octocat: auto-merge'
      then:
      - disableAutoMerge
