id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Push to live branch (publish)
      frequencies:
      - hourly:
          hour: 3
      filters: []
      actions:
      - createPullRequest:
          head: main
          base: live
          title: Merge main into live
          body: Please don't squash-merge this PR.
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - targetsBranch:
          branch: live
      then:
      - addLabel:
          label: auto-merge
      description: Label PRs to live
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: auto-merge
      then:
      - enableAutoMerge:
          mergeMethod: Merge
      description: Auto-merge main to live
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: auto-merge
      then:
      - disableAutoMerge
      description: Auto-merge main to live
onFailure: 
onSuccess: 
