name: GitOps.PullRequestIssueManagement
description: Schedule a PR from main to live
resource: repository

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: Push to live branch (publish)
        frequencies:
          - hourly:
              hour: 3
        filters: []
        actions:
          - createPullRequest:
              head: main
              base: live
              title: Merge main into live
              body: Please don't squash-merge this PR.
